---
# Source: fcfs-csi-driver/templates/clusterrolebinding-provisioner.yaml
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: fcfs-csi-provisioner-binding
  labels:
    app.kubernetes.io/name: fcfs-csi-driver
subjects:
  - kind: ServiceAccount
    name: fcfs-csi-controller-sa
    namespace: default
roleRef:
  kind: ClusterRole
  name: fcfs-external-provisioner-role
  apiGroup: rbac.authorization.k8s.io
