---
# Source: fcfs-csi-driver/templates/fastcfs-client-configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: "fastcfs-client-config"
  labels:
    app.kubernetes.io/name: fcfs-csi-driver
data:
  fdir-cluster: |

    # config the auth config filename
    auth_config_filename = ../auth/auth.conf

    [group-cluster]
    # the default cluster port
    port = 11011

    [group-service]
    # the default service port
    port = 11012

    ## Important:server group mark, don't modify this line.

    # config a server instance
    # section format: [server-$id]
    # server id is a 32 bits natural number (1, 2, 3 etc.),
    [server-1]

    # format: host[:port]
    # host can be an IP address or a hostname
    # IP address is recommended
    # can occur more than once
    host = 192.168.99.181
  fstore-cluster: |
    #
    # the server group is a physical concept, the data under the same server group
    # is the same (redundant or backup).
    #
    # the data group is a logical or virtual concept, its purpose is to facilitate
    # cluster expansion.
    #
    # cluster expansion: migrate one or more data group(s) to one or more new server group(s).
    # data migration: restart after the mappings from data group to server group modified,
    # the data replication will be completed automatically.
    #
    # in order to facilitate cluster expansion, there is a one to many relationship
    # between the server groups and the data groups.
    # 1 : 64 (server groups : data groups) is recommended.
    #
    # data is hashed to the server group according to block hash code % the data groups.
    # once the number of data groups is set, it can NOT be changed, otherwise
    # the data access will be confused!
    #
    # if you want to change the number of data groups after the formal running of
    # the cluster, you MUST create a new cluster and migrate the data to it.

    # the group count of the servers / instances
    server_group_count = 1

    # all data groups must be mapped to the server group(s) without omission.
    # once the number of data groups is set, it can NOT be changed, otherwise
    # the data access will be confused!
    data_group_count = 64

    # config the auth config filename
    auth_config_filename = ../auth/auth.conf

    [group-cluster]
    # the default cluster port
    port = 21014

    [group-replica]
    # the default replica port
    port = 21015

    [group-service]
    # the default service port
    port = 21016

    ## Important:server group mark, don't modify this line.

    # the server group id based 1
    # the data under the same server group is the same (redundant or backup)
    [server-group-1]

    # config one or more server id(s)
    ## multiple server ids separated by comma(s).
    ## [start, end] for range, including start and end.
    # this parameter can occurs more than once.
    server_ids = 1

    # the data group id based 1. the formats as:
    ##  * multiple data group ids separated by comma(s).
    ##  * [start, end] for range, including start and end.
    # this parameter can occurs more than once.
    data_group_ids = [1, 64]

    # config a server
    # section format: [server-$id]
    # server id is a 32 bits natural number (1, 2, 3 etc.),
    [server-1]

    # format: host[:port]
    # host can be an IP address or a hostname
    # IP address is recommended
    # can occur more than once
    host = 192.168.99.181
  auth-cluster: |

    [group-cluster]
    # the default cluster port
    port = 31011

    [group-service]
    # the default service port
    port = 31012

    ## Important:server group mark, don't modify this line.

    # config a server
    # section format: [server-$id]
    # server id is a 32 bits natural number (1, 2, 3 etc.),
    [server-1]

    # format: host[:port]
    # host can be an IP address or a hostname
    # IP address is recommended
    # can occur more than once
    host = 192.168.99.181
  auth-config: |
    # enable / disable authentication
    # default value is false
    auth_enabled = true

    # the config filename of auth client
    client_config_filename = client.conf
  auth-client: |
    # config the cluster servers
    cluster_config_filename = cluster.conf

  fuse-config: |
    [idempotency]
    # if enable RPC idempotency for highest level consistency
    # default value is false
    enabled = true

    # thread stack size, should >= 320KB
    thread_stack_size = 512KB


    [FastDIR]

    # config the cluster servers
    cluster_config_filename = ../fdir/cluster.conf

    # if use sys lock for file append and truncate to avoid conflict
    # set true when the files appended or truncated by many nodes (FUSE instances)
    # default value is false
    use_sys_lock_for_append = false

    # if async report file attributes (size, modify time etc.) to the FastDIR server
    # default value is true
    async_report_enabled = true

    # the interval in milliseconds for async report file attributes to the FastDIR server
    # default value is 100 ms
    async_report_interval_ms = 100


    [FastStore]
    # config the cluster servers and groups
    cluster_config_filename = ../fstore/cluster.conf

    [write-combine]
    # if enable write combine feature for FastStore
    # default value is true
    enabled = true

    [read-ahead]
    # if enable read ahead feature for FastStore
    # default value is true
    enabled = true


    [FUSE]

    # if use separate fuse device fd for each thread
    # set to true for more high performance
    # default value is false
    clone_fd = true

    # access permissions for other users
    # the values are:
    ##  all for all users
    ##  root for root only
    ##  empty or other values for none
    allow_others = all

    # cache time for file attribute in seconds
    # default value is 1.0s
    attribute_timeout = 5.0

    # cache time for file entry in seconds
    # default value is 1.0s
    entry_timeout = 5.0
