# WARNING: this is only for testing purposes. Do not install in a production
# cluster.
#
# This exposes the fcfs's Unix domain csi.sock as a TCP port to the
# outside world. The mapping from Unix domain socket to TCP is done
# by socat.
#
# This is useful for testing with csi-sanity or csc.

apiVersion: v1
kind: Service
metadata:
  name: fcfs-service
spec:
  type: NodePort
  selector:
    app: csi-fcfs-socat
  ports:
  - port: 10000 # fixed port inside the pod, dynamically allocated port outside
---
kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: csi-fcfs-socat
spec:
  serviceName: "csi-fcfs-socat"
  replicas: 1
  selector:
    matchLabels:
      app: csi-fcfs-socat
  template:
    metadata:
      labels:
        app: csi-fcfs-socat
    spec:
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - csi-fcfsplugin
            topologyKey: kubernetes.io/hostname
      containers:
        - name: socat
          image: alpine/socat:1.0.3
          args:
            - tcp-listen:10000,fork,reuseaddr
            - unix-connect:/csi/csi.sock
          securityContext:
            # This is necessary only for systems with SELinux, where
            # non-privileged sidecar containers cannot access unix domain socket
            # created by privileged CSI driver container.
            privileged: true
          volumeMounts:
          - mountPath: /csi
            name: socket-dir
      volumes:
        - hostPath:
            path: /var/lib/kubelet/plugins/csi-fcfs
            type: DirectoryOrCreate
          name: socket-dir
