kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: csi-fcfs-resizer
spec:
  serviceName: "csi-fcfs-resizer"
  replicas: 1
  selector:
    matchLabels:
      app: csi-fcfs-resizer
  template:
    metadata:
      labels:
        app: csi-fcfs-resizer
    spec:
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - csi-fcfsplugin
            topologyKey: kubernetes.io/hostname
      serviceAccountName: csi-resizer
      containers:
        - name: csi-resizer
          image: k8s.gcr.io/sig-storage/csi-resizer:v1.1.0
          args:
            - -v=5
            - -csi-address=/csi/csi.sock
          securityContext:
            # This is necessary only for systems with SELinux, where
            # non-privileged sidecar containers cannot access unix domain socket
            # created by privileged CSI driver container.
            privileged: true
          volumeMounts:
            - mountPath: /csi
              name: socket-dir
      volumes:
        - hostPath:
            path: /var/lib/kubelet/plugins/csi-fcfs
            type: DirectoryOrCreate
          name: socket-dir
