apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: csi-fcfs-pvc
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: csi-fcfs-sc # defined in csi-storageclass.yaml