---
apiVersion: v1
kind: Secret
metadata:
  name: csi-fcfs-secret
  namespace: default
stringData:

  # Required for provisioned volumes
  adminName: admin
  adminSecretKey: b645f5a893a0a01a13bf4807afc5995c
  userName: admin
  userSecretKey: b645f5a893a0a01a13bf4807afc5995c
