---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: csi-fcfsfused-proxy
spec:
  selector:
    matchLabels:
      app: csi-fcfsfused-proxy
  template:
    metadata:
      labels:
        app: csi-fcfsfused-proxy
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: type
                    operator: NotIn
                    values:
                      - virtual-kubelet
      containers:
      - command:
          - nsenter
          - '--target'
          - '1'
          - '--mount'
          - '--uts'
          - '--ipc'
          - '--net'
          - '--pid'
          - '--'
          - sh
          - '-c'
          - |
            set -xe
            rpm -ivh http://www.fastken.com/yumrepo/el8/x86_64/FastOSrepo-1.0.0-1.el8.x86_64.rpm
            yum install wget FastCFS-fused -y
            # download fcfs-fused-proxy .rpm package
            wget https://github.com/happyfish100/fastcfs-csi/raw/master/deploy/fcfsfused-proxy/v0.1.0/fcfsfused-proxy-v0.1.0.rpm -O /tmp/fcfsfused-proxy-v0.1.0.rpm
            rpm -ivh /tmp/fcfsfused-proxy-v0.1.0.rpm
            mkdir -p /var/lib/kubelet/plugins/fcfs.csi.vazmin.github.io
            echo "Enabling fcfsfused-proxy systemctl service"
            systemctl daemon-reload
            systemctl enable fcfsfused-proxy
            systemctl start fcfsfused-proxy
            echo "removing the file: /tmp/fcfsfused-proxy-v0.1.0.rpm"
            rm /tmp/fcfsfused-proxy-v0.1.0.rpm
            echo "waiting for fcfsfused-proxy service to start"
            sleep 3s
            # tail fcfsfused-proxy logs
            journalctl -u fcfsfused-proxy -f
        image: centos:centos8
        imagePullPolicy: IfNotPresent
        name: sysctl-install-fcfsfused-proxy
        resources:
          requests:
            cpu: 10m
        securityContext:
          privileged: true
      dnsPolicy: ClusterFirstWithHostNet
      hostNetwork: true
      hostPID: true
      nodeSelector:
        kubernetes.io/os: linux
      priorityClassName: system-node-critical
      restartPolicy: Always
      tolerations:
        - operator: Exists
